# Generated by Django 3.2.5 on 2022-06-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_add_rating_data'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='movie',
        ),
        migrations.AddField(
            model_name='post',
            name='movie',
            field=models.ManyToManyField(blank=True, to='movie.Movie'),
        ),
    ]
