# Generated by Django 3.2.5 on 2022-06-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('image_url', models.URLField(blank=True)),
                ('releaseDate', models.DateTimeField()),
                ('runtimeMins', models.CharField(max_length=10)),
                ('overview', models.CharField(max_length=2000)),
                ('keywords', models.CharField(max_length=200)),
                ('directors', models.ManyToManyField(related_name='movies', to='movie.Director')),
                ('genres', models.ManyToManyField(related_name='movies', to='movie.Genres')),
                ('stars', models.ManyToManyField(related_name='movies', to='movie.Star')),
            ],
        ),
    ]
