# Generated by Django 3.2.5 on 2022-06-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_add_genres_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='releaseDate',
            field=models.DateField(),
        ),
    ]
